@include('frontend/layouts/head')
@include('frontend/layouts/header')
@include('frontend/layouts/hero')
@include('frontend/layouts/team')
@include('frontend/layouts/tournament')
@include('frontend/layouts/player')
@include('frontend/layouts/latest')
@include('frontend/layouts/footer')